FRW-1166 Dynamic Store integration
spryker-shop/b2b-demo-shop pull request #173
Opened 2023-05-04 12:42 UTC by yaroslav-spryker

#### Overview

- Ticket: https://spryker.atlassian.net/browse/FRW-1166

2023-05-15 12:48 UTC, olhalivitchuk approved these changes

2023-05-15 13:43 UTC, asmarovydlo requested changes

2023-05-15 13:43 UTC, asmarovydlo commented on composer.json
> +        "spryker/acl-entity": "^1.9",
ACL entity is currently used only in Merchant Portal, which is Marketplace-related functionality, it should not be part of `b2b-demoshop`, only of `b2b-mp` and `b2c-mp`.
Please remove the dependency, and get rid of all related changes. (Including new entities, and query classes and `<behavior name="\Spryker\Zed\AclEntity\Persistence\Propel\Behavior\AclEntityBehavior"/>`)

2023-05-24 07:50 UTC, asmarovydlo requested changes

2023-05-24 08:06 UTC, yaroslav-spryker commented on config/install/destructive.dynamic-store.yml
> +    scheduler-start:
We don't need this for nonsplit, I will create a PR to fix this

2023-05-24 08:06 UTC, yaroslav-spryker commented on config/install/docker.yml
> -
We don't need this for nonsplit, I will create a PR to fix this

2023-05-24 09:42 UTC, asmarovydlo approved these changes

2023-05-24 13:28 UTC, merged