Feature/frw 1893/master data exchange api
spryker-shop/b2b-demo-shop pull request #279
Opened 2023-09-29 14:11 UTC by dimitriyTsemma

Tickets: 
- https://spryker.atlassian.net/browse/FRW-2249
- https://spryker.atlassian.net/browse/FRW-5799
- https://spryker.atlassian.net/browse/FRW-5841
- https://spryker.atlassian.net/browse/FRW-6085
- https://spryker.atlassian.net/browse/FRW-2434
- https://spryker.atlassian.net/browse/FRW-6035
- https://spryker.atlassian.net/browse/FRW-2426
- https://spryker.atlassian.net/browse/FRW-1893
- https://spryker.atlassian.net/browse/FRW-2211

2023-10-02 16:29 UTC, yaroslav-spryker approved these changes

2023-10-03 07:27 UTC, geega approved these changes

2023-10-03 11:52 UTC, asmarovydlo requested changes
Please fix issue with composer, see GithubActions errors

2023-10-03 12:29 UTC, asmarovydlo approved these changes

2023-10-04 15:52 UTC, merged