FRW-9206: update artefacts storage structure
spryker-shop/b2b-demo-shop pull request #550
Opened 2024-12-03 19:07 UTC by annakotiuk

#### Overview

- Ticket: URL_HERE

###### Optional

- Core PR: URL_HERE

###### Change log

{Relevant changes for project level go here.}

2024-12-18 16:09 UTC, olhalivitchuk requested changes

2024-12-18 16:09 UTC, olhalivitchuk commented on .github/workflows/robot-ui-e2e-tests.yml
> +                    AWS_DEFAULT_REGION=${{env.ROBOT_TESTS_ARTIFACTS_BUCKET_REGION}} AWS_ACCESS_KEY_ID=${{ secrets.ROBOT_TESTS_ARTIFACTS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.ROBOT_TESTS_ARTIFACTS_
Why the group is PHP8.3MariaDB if the job is for PHP 8.2?

Please check other places as well

2024-12-20 15:06 UTC, olhalivitchuk approved these changes

2024-12-20 17:30 UTC, asmarovydlo commented on .github/workflows/ci.yml
> +                    AWS_DEFAULT_REGION=${{env.ROBOT_TESTS_ARTIFACTS_BUCKET_REGION}} AWS_ACCESS_KEY_ID=${{ secrets.ROBOT_TESTS_ARTIFACTS_KEY }} AWS_SECRET_ACCESS_KEY=${{ secrets.ROBOT_TESTS_ARTIFACTS_
8.3 👍

2024-12-24 10:30 UTC, merged